### PR TITLE
setup travis

### PR DESCRIPTION
**Pull request by makandre**
Signed-off-by: Andrew Mak <makandre@ca.ibm.com>

### CODE REVIEW

**Comment by makandre** [comment]
Hi @garypicher, as discussed I'm adding travis build to this repo based on the examples you gave.  Please take a look at these changes.  Thanks.

**Review by garypicher — APPROVED** [review]
Looks good - let me know when you want this enabled to run automatically and I'll set it up for you.

**Comment by makandre** [comment]
@garypicher Yes please could you enable it?  I would also like to test it.  Would merging this PR trigger a build?

**Comment by garypicher** [comment]
@makandre Okay, it is all set up now!  Yes, merging this PR will trigger a build.

**Pull request merged**
